var universities=new Array(
    "Acadia",
    "Alberta",
    "Athabasca",
    "Bishop",
    "Brandon",
    "Brock",
    "Calgary",
    "Carleton",
    "Concordia",
    "Dalhousie",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laval",
    "Lethbridge",
    "Manitoba",
    "McGill",
    "McMaster",
    "Memorial",
    "Moncton",
    "Montreal",
    "Mt.Allison",
    "Mt. St.Vincent",
    "New Brunswick",
    "Nipissing",
    "Northern BC",
    "Ottawa",
    "PEI",
    "Quebec",
    "Queen's",
    "Queen's Engineering",
    "Regina",
    "RMC/CMR",
    "Royal Roads",
    "Ryerson",
    "Saskatchewan",
    "Sherbrooke",
    "Simon Fraser",
    "St.Francis Xavier",
    "St.Mary's",
    "St.Thomas",
    "Ste-Anne",
    "Toronto",
    "Trent",
    "Trinity Western",
    "UBC",
    "UOIT",
    "Victoria",
    "Waterloo",
    "Western",
    "Laurier",
    "Windsor",
    "Winnipeg",
    "York"
);