//Conversion Factors from: http://studentsuccess.mcmaster.ca/students/tools/gpa-conversion-chart.html
//Note: Assuming a pecent converstion factor of 3 and letter factor of 7 for unlisted factors on the website

/*First number represents the percentage conversion factor, the second
number represents the letter grade conversion factor*/
var universities=new Array(
    new Array("Acadia",3,7),
    new Array("Alberta",3,7),
    new Array("Athabasca",3,7),
    new Array("Bishop",3,7),
    new Array("Brandon",3,7),
    new Array("Brock",3,7),
    new Array("Calgary",3,7),
    new Array("Carleton",3,7),
    new Array("Concordia",3,7),
    new Array("Dalhousie",3,7),
    new Array("Guelph",3,7),
    new Array("Lakehead",3,7),
    new Array("Laurentian",3,7),
    new Array("Laval",3,7),
    new Array("Lethbridge",3,7),
    new Array("Manitoba",3,9),
    new Array("McGill",3,8),
    new Array("McMaster",3,7),
    new Array("Memorial",6,7),
    new Array("Moncton",3,7),
    new Array("Montreal",3,7),
    new Array("Mt.Allison",3,7),
    new Array("Mt. St.Vincent",3,7),
    new Array("New Brunswick",3,7),
    new Array("Nipissing",3,7),
    new Array("Northern BC",3,7),
    new Array("Ottawa",3,7),
    new Array("PEI",3,7),
    new Array("Quebec",3,7),
    new Array("Queen's",3,7),
    new Array("Queen's Engineering",4,7),
    new Array("Regina",3,7),
    new Array("RMC/CMR",4,7),
    new Array("Royal Roads",3,7),
    new Array("Ryerson",3,7),
    new Array("Saskatchewan",3,7),
    new Array("Sherbrooke",3,7),
    new Array("Simon Fraser",3,7),
    new Array("St.Francis Xavier",3,7),
    new Array("St.Mary's",3,7),
    new Array("St.Thomas",3,7),
    new Array("Ste-Anne",3,7),
    new Array("Toronto",3,7),
    new Array("Trent",3,7),
    new Array("Trinity Western",3,7),
    new Array("UBC",3,7),
    new Array("UOIT",3,7),
    new Array("Victoria",3,7),
    new Array("Waterloo",3,7),
    new Array("Western",3,7),
    new Array("Laurier",3,7),
    new Array("Windsor",3,7),
    new Array("Winnipeg",3,7),
    new Array("York",3,9)
);